### ISSUE TITLE
missing notepad.res

### ISSUE THREAD

**Issue by biax** [przemoc/npplauncher#4]
as you know, theres recently a native 64 bit version of notepad++

im trying to modify the code to make a launcher.

T:\nppl\npplauncher-master>i686-w64-mingw32-gcc -Wall -O2 -std=c99 notepad.c notepad.res -o i686/notepad.exe -mwindows -s
i686-w64-mingw32-gcc: error: notepad.res: No such file or directory

T:\nppl\npplauncher-master>i686-w64-mingw32-gcc -Wall -O2 -std=c99 notepad.c notepad.res -o i686/wait_for_exit/notepad.exe -mwindows -s -DWAIT_FOR_EXIT=1
i686-w64-mingw32-gcc: error: notepad.res: No such file or directory

where do i get this file notepad.res?

**Comment by przemoc** [comment]
> as you know, theres recently a native 64 bit version of notepad++

Actually I haven't used Notepad++ for some time, but visiting homepage revealed, that there is indeed [x64 version](https://notepad-plus-plus.org/news/notepad-7-released.html) available nowadays.

> where do i get this file notepad.res?

It's generated from `notepad.rc` using `windres` tool. Check `build*.cmd` files for details.

**Comment by biax** [comment]
Thanks for the response. Fixed the batch script a little. Working now. Thanks for sharing your code.
